---
nexdeck_node: "atlas"
nexdeck_vmid: "129"
nexdeck_hostname: "nexdeck-nash"
nexdeck_storage: "local-zfs"
nexdeck_template: ""
nexdeck_cores: 2
nexdeck_memory: 2048
nexdeck_disk: 12
nexdeck_bridge: "vmbr0"
nexdeck_vlan: 40
nexdeck_tags:
  - "dashboard"

nexdeck_version: "0.19.2"
nexdeck_release_url: "https://api.github.com/repos/DerKezorm/nexdeck/tarball/v{{ nexdeck_version }}"
nexdeck_release_checksum: "sha256:b7979c356a4cabb416182371506be7dca93df875a8a6a2424933daf241c5de3e"
nexdeck_port: 8000
