- name: Homelab setup
  hosts: homelab
  become: true
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker
    - role: tailscale
      tags: tailscale
    - role: compose
      tags: compose
