---
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Copy Docker Compose project
  ansible.builtin.copy:
    src: ../../../ComposeFiles/
    dest: /home/{{ ansible_user }}/compose/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Create and enable systemd service
  ansible.builtin.template:
    src: compose-app.service.j2
    dest: /etc/systemd/system/compose-app.service
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Start Docker Compose services
  ansible.builtin.systemd:
    name: compose-app
    state: started
    enabled: true
    daemon_reload: true
