---
wyze_bridge_node: atlas
wyze_bridge_vmid: ""
wyze_bridge_hostname: wyze-bridge-nash
wyze_bridge_storage: local-zfs
wyze_bridge_template: ""
wyze_bridge_cores: 2
wyze_bridge_memory: 2048
wyze_bridge_disk: 8
wyze_bridge_bridge: vmbr0
wyze_bridge_vlan: 40
wyze_bridge_version: "2.10.3"
wyze_bridge_digest: "sha256:af2d638a6d6d52e15ddcfb711e5b905e484b1f519986ad33b9be562b6277b987"
