---
- name: Configure OctoPi
  hosts: octopi_servers
  gather_facts: true
  become: true
  vars_files:
    - vault.yml

  roles:
    - role: network
      tags:
        - network

    - role: octoprint
      tags:
        - octoprint
