---
bambuddy_node: "atlas"
bambuddy_vmid: ""
bambuddy_hostname: "bambuddy-nash"
bambuddy_storage: "local-zfs"
bambuddy_template: ""
bambuddy_cores: 2
bambuddy_memory: 2048
bambuddy_disk: 10
bambuddy_bridge: "vmbr0"
bambuddy_vlan: 40
bambuddy_tags:
  - "3d-printing"

bambuddy_version: "1.2.5.5"
bambuddy_release_url: >-
  https://api.github.com/repos/maziggy/bambuddy/tarball/v{{ bambuddy_version }}
bambuddy_release_checksum: "sha256:da8d97fd7bfefd3742fd52e622f30d6ddc9efa1f5b30bb079f9bb55091474204"
bambuddy_install_dir: "/opt/bambuddy"
bambuddy_bind_host: "0.0.0.0"
bambuddy_port: 8000
