---
prowlarr_node: "atlas"
prowlarr_vmid: "104"
prowlarr_hostname: "prowlarr-nash"
prowlarr_storage: "local-zfs"
prowlarr_template: ""  # auto-detect latest debian-1[23]-standard if empty
prowlarr_cores: 1
prowlarr_memory: 1024
prowlarr_disk: 4
prowlarr_bridge: "vmbr0"
prowlarr_vlan: 40
prowlarr_tags:
  - media

prowlarr_version: "2.5.2.5491"
prowlarr_release_url: >-
  https://github.com/Prowlarr/Prowlarr/releases/download/v{{ prowlarr_version
  }}/Prowlarr.master.{{ prowlarr_version }}.linux-core-x64.tar.gz
prowlarr_release_checksum: "sha256:22fe95742869d7af5e16d420c7889185579152ea8324be6c6e4e3cd011f4c37b"
prowlarr_install_dir: "/opt/Prowlarr"
prowlarr_data_dir: "/var/lib/prowlarr"
prowlarr_port: 9696
prowlarr_health_url: "http://10.10.40.87:{{ prowlarr_port }}"
