---
- name: Install NFS client packages
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Create NFS mount point
  ansible.builtin.file:
    path: "{{ nfs_mount_path }}"
    state: directory
    mode: '0755'

- name: Mount NFS share
  ansible.posix.mount:
    path: "{{ nfs_mount_path }}"
    src: "{{ nfs_mount_server }}:{{ nfs_mount_export_path }}"
    fstype: nfs
    opts: "{{ nfs_mount_opts }}"
    state: mounted
