- name: Clean up old Docker GPG key from trusted.gpg
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: absent
  when: ansible_os_family == "Debian"
  ignore_errors: true

- name: Find and remove any old docker repository files
  ansible.builtin.shell: "find /etc/apt/sources.list.d -type f -name '*docker*.list' -delete"
  register: remove_docker_repo_files
  changed_when: remove_docker_repo_files.stdout != ""
  when: ansible_os_family == "Debian"

- name: Remove any old docker repository lines from main sources.list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    state: absent
    regexp: '.*download.docker.com.*'
  when: ansible_os_family == "Debian"

- name: Clean up old Docker GPG key file
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    state: absent
  when: ansible_os_family == "Debian"

- name: Ensure /etc/apt/keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: Add Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true
  when: ansible_os_family == "Debian"

- name: Get dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Add Docker repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch={{ dpkg_arch.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable"
    mode: '0644'
  when: ansible_os_family == "Debian"
  notify:
    - Update apt cache

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_os_family == "Debian"
  notify:
    - Start and enable Docker service

- name: Add Docker repository for Fedora
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo=https://download.docker.com/linux/fedora/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_os_family == "Fedora"

- name: Install Docker on Fedora
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_os_family == "Fedora"
  notify:
    - Start and enable Docker service
