---
radarr_node: "prometheus"
radarr_vmid: "111"
radarr_hostname: "radarr-nash"
radarr_storage: "local-zfs"
radarr_template: ""  # auto-detect latest debian-1[23]-standard if empty
radarr_cores: 2
radarr_memory: 1024
radarr_disk: 4
radarr_bridge: "vmbr0"
radarr_vlan: 40
radarr_tags:
  - "arr"

radarr_version: "6.4.4.10685"
radarr_release_url: >-
  https://github.com/Radarr/Radarr/releases/download/v{{ radarr_version
  }}/Radarr.master.{{ radarr_version }}.linux-core-x64.tar.gz
radarr_release_checksum: "sha256:a1d726129535e739d4efaf93b5fdd771bb1c78349f55ceac70e365e37b5a12a3"
radarr_install_dir: "/opt/Radarr"
radarr_data_dir: "/var/lib/radarr"
radarr_backup_dir: "/opt/radarr-backups"
radarr_user: "media"

radarr_port: 7878
radarr_health_url: "http://10.10.40.131:{{ radarr_port }}/ping"
