---
octoprint_user: pi
octoprint_group: pi
octoprint_basedir: "/home/{{ octoprint_user }}/.octoprint"
octoprint_venv: "/home/{{ octoprint_user }}/oprint"
octoprint_service: octoprint
octoprint_reset_existing_password: false
octoprint_gcode_source: ""
octoprint_gcode_destination: "{{ octoprint_basedir }}/uploads"
octoprint_temperature_profiles: []
octoprint_plugin_system_packages: []
octoprint_plugins: []
octoprint_settings: []
octoprint_serial:
  port: null
  baudrate: null
  autoconnect: true
